### ISSUE TITLE
It is not working in chrome

### ISSUE THREAD

**Issue by anshul-ctinfotech** [GoodSpeech/good-speech-web-client#2]
HI thanks for project 
I have run project demo in chrome browser but it still not supported.

https://imgur.com/NIIV1O9

**Comment by sljavi** [comment]
Thanks for reporting the issue, I'll review ASAP and post here as soon as it is resolved.

**Comment by sljavi** [comment]
@anshul-ctinfotech I just fixed the issue you can give another try now. Thanks for reporting it.
